### ISSUE TITLE
i have some question or suggestion.

### ISSUE THREAD

**Issue by study4u** [jackwanders/GalleryView#1]
i have some question or suggestion.
sorry for this.
i want to display extra layer on gv_panel.
because i want to display other html tag in each of slide image.
so example...
your code like that....
&lt;li&gt;
&lt;img thumbnail slide title&gt;
&lt;/li&gt;

but 
i want to add like that
&lt;li&gt;
&lt;img slide&gt;
&lt;div&gt; other html or object tag &lt;/div&gt;
&lt;/li&gt;

is it possible?

anyway thanks a lot everything~
have a nice day~

thanks.

**Comment by scottschluer** [comment]
LOL I think I just suggested the exact same thing at the exact same time.

**Comment by study4u** [comment]
i just add some script in js source.
this is sample~
http://studyu.cafe24.com/xe/index.php?mid=ext_study4u&skin=GalleryView&colorset=default

thanks~
