### ISSUE TITLE
Would like ability to add custom HTML to a slide

### ISSUE THREAD

**Issue by scottschluer** [jackwanders/GalleryView#2]
I've been using your older version of GalleryView and one of the reasons I chose it is because I can insert custom HTML into a slide instead of an image. I use it to display YouTube videos (with a custom video icon as the thumbnail) in the gallery rotation. I can't upgrade to the next version until this is supported, and I've been watching for months hoping to see this added. 

You can see the gallery in action at http://www.equispot.com. Click on the "Show Video Ads" link from the home page to see ads that have galleries containing both video and images.

Any thoughts as to when this might be implemented in your latest version?

**Comment by study4u** [comment]
wow... 

thats it~ ^^
yes. i want to display Youtube or other custom html~ not only image~
thanks~

**Comment by study4u** [comment]
you may visit my web site~ i have many example~ include galleryview~
http://studyu.cafe24.com
sorry this site for korean~ but you can get it~
or use below.. this is media widget for XE.. this is also free
http://www.xpressengine.com/index.php?mid=download&package_srl=20612563

if you want install XE i can help you. no need pay for this~

thanks~

**Comment by jackwanders** [comment]
I've closed out the duplicate ticket as the request was the same in both. For this new version of GalleryView, I have narrowed my focus initially to deal only with image-based galleries. Once the script is feature-complete and relatively bug free, I will work on incorporating features that were dropped from the original version.

**Comment by netconstructor** [comment]
I would like to add a +1 on this request. I have been looking for an alternative to jquery cycle and this seems like a perfect fit except for the lack of being able to utilize it on your own elements such as a custom div

**Comment by Mixa032** [comment]
I'm also adding this request. I wanted to wrap every image with link, but that doesnt work...

**Comment by ranilsonpaiva** [comment]
I also need to wrap the images with links. Is there any other way?

**Comment by ipoweb** [comment]
me too for links

**Comment by ipoweb** [comment]
me too for links

**Comment by ipoweb** [comment]
me too for links

**Comment by cenzistiles** [comment]
me too, I would like to include a a iframe in there if possible.
